TODO.md
scripts/convertConfig.ts
src/lib/components/AudioBar.svelte
src/routes/data/audio.js

Now handles multiple audio sources. Gives an error message when attempts to use FCBH audio.

Audio sources

---

TODO.md
scripts/convertConfig.ts

color information is now in config.js

convert color information

---

.gitignore
package.json
scripts/Task.ts
scripts/convertAbout.ts
scripts/convertBooks.ts
scripts/convertConfig.ts
scripts/convertMedia.ts
scripts/index.ts

* Add verbosity level to help with tracking down issues
* Fix writing-system not required to have display-names
* Fix font-name not required for font
* Fix len and size not required for audio filename

Fix Convert Config

---

scripts/convertConfig.ts

Demonstrate how to modify the ConvertConfig script to parse XML into a usable JSON format.  Here are the steps that I did.
1) created sample data in Scripture App Builder (figuring out what elements were optional)
2) ran PWA Data Files
3) looked at data/appdef.xml (used VS Code's Format Document to make it easier to read)
```xml
<menu-items>
<menu-item type="website">
<title>
<t lang="en">Visit our Website</t>
</title>
<link>
<t lang="default">https://software.sil.org</t>
</link>
<images type="menu-item">
<image width="24" height="24">ic_globe_black_24px.png</image>
<image width="48" height="48">ic_globe_black_48px.png</image>
<image width="72" height="72">ic_globe_black_72px.png</image>
</images>
</menu-item>
<menu-item type="facebook">
<title>
<t lang="en">Find us on Facebook</t> …
```

ConvertConfig: menu-items

---

src/lib/components/BookSelector.svelte
src/lib/components/Dropdown.svelte
src/lib/components/SelectList.svelte

Created a "SelectList" similar to SelectGrid.
Got relatively far, hit a roadblock with the "Book, Chapter, and Verse" tabs at the top. They're in the same list format as the book collections.

Book navigation

---

src/lib/components/AudioBar.svelte
src/lib/icons/audio/PauseIcon.svelte
src/lib/icons/audio/PlayFillCircleIcon.svelte
src/lib/icons/audio/PlayIcon.svelte
src/lib/icons/audio/PlayOutlineCircleIcon.svelte
src/lib/icons/audio/index.js
src/routes/+page.svelte

* fix the audio bar layout so that different sized play icons will work
* add additional play icons
* add switching play icon based on config

Implement play icons

---

src/lib/components/AudioBar.svelte
src/lib/data/stores.js
src/routes/+page.svelte

The playMode rotates through these states: continue (to next chapter), stop (at the end of the chapter, repeat page, repeat selection.
On Android, if the current option is repeat selection and the chapter is changed to another chapter without timing (even chapter without audio), the mode is reset to continue.

Implement playMode store and toolbar icon

---

src/lib/data/stores.js
src/lib/scripts/verseSelectUtil.ts

A follow up PR will need to be added to prevent the verse number and footnote text from being displayed.  Comment code is in the verseSelectUtil.ts that shows how you can parse through the selected verses in order

Save selected text in store

---

scripts/convertConfig.ts

* No errors if there are no videos
* Properly check for empty dir (synchronously)

Fix issues with recent changes to convertConfig.ts

---

src/routes/settings/+page.svelte

* handle JSON elements not present
* handle dark mode for text

Fix settings

---

src/routes/+page.svelte

* Improves the condition height of the scrolling area
* Depends on change in SAB to generate a single border.png

Implement Borders

---

src/lib/data/stores/setting.ts
src/lib/data/stores/view.js
src/routes/settings/+page.svelte

* default to sidebar hiding all the time (on desktop and mobile)
* add development store
* when development enabled, add "Desktop Sidebar" Setting

Change sidebar on desktop

---

.gitignore
package.json
scripts/convertManifest.ts
src/app.html
src/lib/components/AudioBar.svelte
src/lib/components/ScriptureViewSofria.svelte
src/lib/components/Sidebar.svelte
src/routes/+layout.svelte
src/routes/+page.svelte
src/service-worker.js
static/sab-stylesheet.css
svelte.config.js

* Add Service Worker
* Change manifest.webmanifest to manifest.json
* Enable PWA to be served from sub directory

Add PWA mechanisms

---

src/lib/components/CollectionSelector.svelte
src/lib/components/Modal.svelte
src/routes/+page.svelte
src/routes/layout/+page.svelte

Adding support for modals in the PWA. A unique ID will need to be assigned to each since a label button corresponds to the physical pop up.

Modal Component

---

src/lib/components/AudioBar.svelte
src/lib/components/ScriptureViewSofria.svelte
src/lib/components/ScrolledContent.svelte
src/lib/scripts/configUtils.ts
src/lib/scripts/parsePhrase.ts
src/lib/scripts/verseSelectUtil.ts
src/routes/+page.svelte

This became over large.  Each commit should probably have been a separate pr.
Fixed a small issue where scrolling was set for the wrong div so audio scrolling wasn't working.
Moved the remainder of the store references so that they were passed in for ScriptureViewSofria
Fixed a small issue where audio highlighting failed after going to a non audio chapter and back
Reimplemented parsePhrases to more closely model the android version
Implemented one verse per line view setting.
When reviewing, it may be easier to view each commit individually.

View enhancements

---

src/lib/components/Navbar.svelte
src/lib/icons/ArrowBackIcon.svelte
src/lib/icons/index.js

When not on the home page, change the hamburger menu icon to a back arrow icon and navigate back to the home page

Implement back arrow when not on home page

---

src/lib/components/Navbar.svelte
src/lib/icons/ArrowForwardIcon.svelte
src/lib/icons/index.js

Umm ... it is waaaay to easy ...

Add RTL support for navbar

---

src/lib/components/Navbar.svelte
src/lib/components/Sidebar.svelte
src/lib/data/stores/interface.js

Rename interfaceDirection to just direction

Implement RTL for sidebar

---

src/lib/components/AudioBar.svelte
src/lib/components/TextAppearanceSelector.svelte
src/routes/search/+page.svelte
src/routes/settings/+page.svelte

rtl support for setting, search and audio bar

---

src/lib/components/ScriptureViewSofria.svelte

Associate the c-drop chapter marker to be associated with the first verse.
Also drop displaying verse number for the first verse.
Correct problems that can occur when a subtitle appears early in the chapter.

Chapter number location

---

src/lib/components/CardMenu.svelte
src/lib/components/TextAppearanceSelector.svelte
src/lib/data/stores/theme.js
src/routes/notes/+page.svelte
src/routes/settings/+page.svelte

* Fix the shish-kibob menu icon theming on cards
* Remove some theming on settings which isn't necessary anymore

Theme monchrome icons

---

src/lib/components/CardMenu.svelte
src/lib/components/ColorCard.svelte
src/lib/components/HistoryCard.svelte
src/lib/components/IconCard.svelte
src/routes/settings/+page.svelte

* Support RTL in the card
* Fix the CardMenu

Convert to DaisyUI

---

src/routes/data/catalog/+server.js

Expose catalog via data endpoint

---

src/lib/components/ScriptureViewSofria.svelte
src/routes/+page.svelte

Move the AudioHighlighting and Scrolling to the scripture page from ScriptureViewSofria.  This fixes two things:
* audio highlighting
* re-rendering of page on scrolling

Move AudioHighlight updating and scrolling to page

---

src/routes/+layout.svelte

This fixes highlighting and text colors when in themes.

data-color-theme needs to be set on #content, not body

---

src/lib/components/BookSelector.svelte
src/lib/components/LayoutOptions.svelte

Reactive definition of bookContent. added .collection to update definition when it changes. Ready for review

Book Selector Reactive Content 

---

src/app.html
src/lib/app.css
src/lib/components/Sidebar.svelte
src/routes/+layout.svelte
src/routes/+page.svelte
src/routes/about/+page.svelte
src/routes/account/+page.svelte
src/routes/bookmarks/+page.svelte
src/routes/highlights/+page.svelte
src/routes/history/+page.svelte
src/routes/notes/+page.svelte
src/routes/search/+page.svelte
src/routes/settings/+page.svelte
src/routes/share/+page.svelte

* Remove fragile height calculations and use pancake stack (https://1linelayouts.glitch.me/)
* Remove blank space on right side on mobile
* Disable user scaling (to make pinch zoom work)

Fix layout using Pancake Stack

---

src/lib/components/HistoryCard.svelte
src/lib/components/LayoutOptions.svelte
src/lib/components/Navbar.svelte
src/lib/data/history.ts
src/lib/data/stores/scripture.js
src/lib/data/stores/store-types.js
src/lib/data/stores/view.js
src/routes/+page.svelte

* remove groupStore wrapper for now since each layout is the same book and chapter, just different collections
* change viewMode to layout and make it an object with mode and optional collections to match data model from config (i.e. config.layouts)

Simplify refs store

---

src/lib/components/Slider.svelte
src/lib/components/TextAppearanceSelector.svelte

- Implemented a slider component for type=range input elements (Slider.svelte) and used it in the TextAppearanceSelector.
- Wrapped the contents of TextAppearanceSelector in a grid div to increase vertical spacing.

Increased TextAppearanceSelector spacing and restyled its sliders (created Slider.svelte).

---

src/lib/components/ScriptureViewSofria.svelte
src/lib/data/stores/annotation.js

* document that they are promises
* use them as promises

Annotiation stores are actually promises

---

src/routes/settings/+page.svelte

This changes the settings font to system font.

change settings font

---

src/routes/+page.svelte

Implement layout visibility in navbar using
`config.mainFeatures['layout-config-change-toolbar-button']`. Implements #288.

Implement layout option menu visibility in navbar

---

src/lib/components/TextSelectionToolbar.svelte
src/lib/data/stores/scripture.js

The reference was set using the bookID which isn't user friendly. Format the reference using the bookName from the book collection.

Use bookname in annotation references

---

src/routes/+page.svelte

Implement viewer button in top left of scripture view. Needs style polish and proper labeling.
Implements #289

#289 Implement viewer

---

src/lib/components/CollectionSelector.svelte
src/lib/components/LayoutOptions.svelte

Fixed issue with inconsistency in constant use that caused book selection to be handled incorrectly.

Layout Selector Hotfix

---

src/lib/components/Navbar.svelte
src/routes/+page.svelte
src/routes/about/+page.svelte
src/routes/account/+page.svelte
src/routes/bookmarks/+page.svelte
src/routes/highlights/+page.svelte
src/routes/history/+page.svelte
src/routes/notes/+page.svelte
src/routes/search/+page.svelte
src/routes/settings/+page.svelte

Changed navbar height to be assessed by the component itself and not in its call in each page. Navbar height calculated using the `NAVBAR_HEIGHT` store of `view.js`. Resolves #326

Chore: Navbar Height #326

---

scripts/convertStyles.ts
src/lib/components/AudioBar.svelte
src/lib/components/CollectionSelector.svelte
src/lib/components/ColorCard.svelte
src/lib/components/HistoryCard.svelte
src/lib/components/IconCard.svelte
src/lib/components/Modal.svelte
src/lib/components/Navbar.svelte
src/lib/components/Sidebar.svelte
src/lib/components/Slider.svelte
src/lib/components/TextAppearanceSelector.svelte
src/routes/+layout.svelte
src/routes/+page.svelte
src/routes/bookmarks/+page.svelte
src/routes/highlights/+page.svelte
src/routes/notes/+page.svelte
src/routes/search/+page.svelte
src/routes/settings/+page.svelte

Partial fix for #340 (for Chrome, but not Firefox)

Fix various RTL issues and simplify implementation

---

src/lib/components/AudioBar.svelte
src/lib/data/audio.ts
src/lib/data/mrucache.ts
src/lib/data/stores/audio.js
src/lib/data/stores/store-types.js
src/lib/scripts/verseSelectUtil.ts
src/routes/+page.svelte

reimplement audio 

---

src/lib/components/ColorCard.svelte
src/lib/components/IconCard.svelte
src/lib/components/TextSelectionToolbar.svelte
src/lib/data/annotation-sort.ts
src/lib/data/bookmarks.ts
src/lib/data/highlights.ts
src/lib/data/notes.ts
src/routes/bookmarks/+page.js
src/routes/bookmarks/+page.svelte
src/routes/highlights/+page.js
src/routes/highlights/+page.svelte
src/routes/notes/+page.js
src/routes/notes/+page.svelte

Done by @davidbbryant.  This fixes merge commit in his branch and fixes lint issue.
Fixes #253 and #254

Feature annotation menus

---

src/lib/components/ScriptureViewSofria.svelte
src/lib/data/audio.ts
src/lib/data/stores/audio.js

* When verse number is clicked audio is played from that verse.
* This fixes #251.
* If the play button or forward/reverse buttons have not been pressed, the verse numbers cannot be clicked.

Implement clicking verse number to change audio position

---

src/lib/components/TextSelectionToolbar.svelte
src/lib/data/highlights.ts
src/lib/data/stores/scripture.js
src/lib/scripts/verseSelectUtil.ts

* Use proskomma query to get raw text of verse
* Delay getting text of selected verses until needed

Selected Verses: get raw text for verses

---

src/lib/data/audio.ts

*removes the thrown error
*fixes get audio to handle a lack of audio
*fixes #363

fix bug in which error message was shown if no audio was available

---

src/lib/components/NoteDialog.svelte
src/lib/data/bookmarks.ts
src/lib/data/highlights.ts
src/lib/data/notes.ts
src/lib/data/stores/view.js
src/routes/+layout.svelte
src/routes/bookmarks/+page.svelte
src/routes/highlights/+page.svelte
src/routes/notes/+page.js
src/routes/notes/+page.svelte

This is a work in progress branch for the edit note feature. The note currently successfully edits but the page does not update properly, despite calling update function.

Implement Edit Note

---

src/lib/data/annotation-share.ts
src/lib/data/share.ts

Use Email & Subject configuration on share

---

scripts/convertConfig.ts
src/lib/components/FontSelector.svelte
src/lib/components/ScriptureViewSofria.svelte
src/lib/components/TextAppearanceSelector.svelte
src/lib/data/stores/scripture.js
src/lib/data/stores/view.js
src/routes/+layout.svelte
src/routes/+page.svelte

Add font selection

---

src/lib/components/AudioBar.svelte
src/lib/data/audio.ts
src/lib/data/stores/audio.js

Adds functionality for each mode with continue, stop, repeat page, and repeat selection.

add functionality for play mode button

---

src/lib/components/AudioBar.svelte

* Remove DaisyUI btn class (which want to be aligned flex-start)
* Manually layout buttons with padding and alignment

Fix audiobar icon spacing with large icons

---

src/lib/components/Dropdown.svelte

See https://github.com/saadeghi/daisyui/discussions/2469

Align dropdown to edge of screen on mobile

---

scripts/convertConfig.ts

* Search
* User Accounts
* Two-pane and Verse-by-verse

Disable incomplete features

---

src/routes/about/+page.js

* need to use {base} for path to get partial
* remove `?raw` since I think it was needed when we tried to import the partial and now that we are loading as resource via fetch it is not needed

Fix about at BUILD_BASE_PATH

---

src/lib/components/HistoryCard.svelte
src/lib/components/IconCard.svelte
src/lib/components/NoteDialog.svelte
src/lib/components/TextSelectionToolbar.svelte
src/routes/bookmarks/+page.js
src/routes/highlights/+page.js
src/routes/history/+page.js
src/routes/notes/+page.js

* Bookmarks, Notes, Highlights, and History would have page exceptions  if collection name was not found.

Make IndexedDB items more resiliant to collection changes

---

scripts/convertConfig.ts
src/lib/components/ScriptureViewSofria.svelte
src/lib/data/stores/setting.ts
src/routes/+page.svelte

* hide settings that are not implemented yet
* fix implementation of hide/show images
* do impleementation of hide/show videos

Settings: verify for initial release

---

scripts/convertBooks.ts
scripts/convertMarkdown.ts
src/lib/components/BookSelector.svelte

* Ignore non-standard book types for now
* Report during conversion which books are being processed (better feedback) and which are not supported
* Only show books in catalog in the book selector
* Start work on Story Picture Book (\page -> \zpage milestone)
* Use stand-alone milestone for videos

Handle Book Types

---

scripts/convertConfig.ts
src/lib/scripts/scripture-reference-utils.ts

Handle additional names in footnotes (Issue #419)

---

src/lib/components/ScriptureViewSofria.svelte

Footnotes display on all collections after it displays once (Issue #455)

---

src/lib/components/ScriptureViewSofria.svelte

* Was crashing app when displaying scripture page

Some videos will not have placement information

---

scripts/convertBooks.ts
src/lib/components/BookSelector.svelte
src/lib/components/ChapterSelector.svelte

* include glossary books in convertBooks
* fix book & chapter navigation

Re-add support for glossaries

---

scripts/convertConfig.ts

* address might not be set (it might not be used)

Fix parsing audio-source download type

---

scripts/convertConfig.ts
src/routes/+page.svelte

Use show-verse-numbers from book level

---

src/lib/components/ScriptureViewSofria.svelte

Fixes #476 
Support all variations of show chapter/position of chapter…/show verse number 1

Display of chapter and first verse number

---

scripts/convertConfig.ts
src/lib/components/ScriptureViewSofria.svelte
src/lib/scripts/configUtils.test.ts
src/lib/scripts/configUtils.ts
src/lib/scripts/numeralSystem.test.ts
src/lib/scripts/numeralSystem.ts

Use Numeral System for Scripture Display

---

scripts/convertBooks.ts

It is valid: \fig filename.jpg\fig*

Figure may not have caption

---

src/lib/components/Sidebar.svelte

Invert menu icons when in Dark mode

---

scripts/convertBooks.ts
src/lib/components/BookSelector.svelte

This is similar to navigating to the introduction if there are no chapters
In Gilaki project, there are books with one chapter with a video.

Navigate to chapter 1 if only one chapter

---

scripts/convertBooks.ts

I switch to using standalone milestones, but they don't seem to be supported by Proskomma

Go back to using milestone-s and milestone-e

---

src/lib/data/scripture.js

This reverts commit a80cda5bd04d0c701291056949538a0660293f17.

Revert "Use SABProskomma (#534)"

---

src/routes/history/+page.svelte

fixes #503.
when there is no history, display the message to indicate that. This way it doesn't look like an error.

display message when there is no history

---

scripts/convertBooks.ts
scripts/convertConfig.ts

Prepare for converting quiz books

Convert books with separate functions

---

convert/convertBadges.ts
src/routes/share/+page.js
src/routes/share/+page.svelte

* Get the languages from convert process instead of hardcoded list
* Try to use interface language for Google Play link, but fallback to languageDefault and then 'en'
* Fallback to languageDefault for App Store image, then to english
* Make sure en App Store image is included for fallback

Fix issues with badges

---

src/lib/data/scripture.js

Allow more of the UI to load before blocking to load the pkf file.

Delay loading the initial pkf file

---

src/lib/components/ScriptureViewSofria.svelte
src/lib/components/TextSelectionToolbar.svelte
src/routes/+page.svelte

Issue #566 
Fixed the text copied button to display a message
Issue: Fading causes audiobar to appear first

Text Copied Pop Up

---

src/lib/components/ScriptureViewSofria.svelte

Issue #509 
Clicking on any Image shows the image in fullscreen and clicking the back arrow closes fullscreen

Illustration Pop Up and Close

---

src/routes/bookmarks/+page.svelte
src/routes/highlights/+page.svelte
src/routes/history/+page.svelte
src/routes/notes/+page.svelte

Issue #591 
Adjusted styling and fonts for bookmarks,  history, notes, and highlights so that it is consitent throughout the app.

Annotations

---

convert/convertConfig.ts

Issue #599
Added the regex expression and vimeo expression so if url matches to the expression it would change to the correct link. 
Problems: Youtube still refuses to connect. Could be access or firewall problem or something else.

Fix Youtube and Vimeo Embed

---

convert/convertContents.ts
src/lib/components/Navbar.svelte
src/lib/components/Sidebar.svelte
src/lib/data/stores/view.js
src/lib/icons/HomeIcon.svelte
src/lib/icons/index.js
src/routes/+page.svelte
src/routes/contents/[id]/+page.js
src/routes/contents/[id]/+page.svelte

links aren't working, there is a lot of work in progress

contents menu

---

.gitignore
convert/convertBooks.ts
convert/convertConfig.ts
convert/convertContents.ts
convert/convertMedia.ts
convert/stringUtils.ts
src/lib/scripts/stringUtils.ts
src/routes/contents/[id]/+page.svelte
src/routes/quiz/[collection]/[id]/+page.svelte

* quiz audio in quiz folder
* contents files (audio, images) in contents folder
* copy plans and songs folder
* support pre-12.0 locations for quiz audio and contents images

Update for AppBuilders 12.0 output changes

---

convert/convertContents.ts
src/routes/contents/[id]/+page.svelte

- fixes issue #612
- converts contents menu layoutMode and layoutCollection into the json
- adds handling for the layoutCollection

handle book collection specification in the contents menu

---

src/lib/video/index.ts

Issue #603
Problem: Full Screen and margins not done

Configure Related Videos and Title Under Videos

---

convert/convertConfig.ts
src/lib/video/index.ts

Issue #600
Added filename matched the source type

Made Video in Assets Play as intended

---

convert/convertConfig.ts

Issue #567
Added if statement to filterFeaturesNotReady
function to hide the restricted book collections

Filtered restricted book collections

---

convert/convertConfig.ts
src/lib/components/ScriptureViewSofria.svelte
src/lib/scripts/milestoneLinks.test.ts
src/lib/scripts/milestoneLinks.ts

Issue #604
Problem: Remote Audio clips were not streamable

Support Remote Audio Clip Streaming

---

convert/convertBooks.ts
convert/convertConfig.ts

Issue #494
Problem: Verse Numbers were still present

Hide Verse Numbers that their corresponding verse is toggled to be hidden

---

convert/convertConfig.ts
src/lib/components/SelectList.svelte

* use ui.button.book-list styles
* switch from tables to flex to use whole width of window
* fix conversion of dp to rem
* use color from style for hover

Fix styling on Book List

---

docs/test-docs/testing-basics.md

Garrett provided a document with regards to how he did tests.

Add test document

---

src/lib/components/ScriptureViewSofria.svelte

Redid the way the text was being handled so that the footnote could be properly added to the header information

Issue #694 - Footnote attached to /s crashes page display

---

src/routes/+layout.svelte

Delay referencing SAB-specific components didn't work in SAB!

Fix layout object references

---

convert/convertConfig.ts

Parsing of layout-collection was changed so that it didn't handle a condition correctly.

Fix parseLayouts to handle layoutCollections

---

convert/convertStyles.ts

When the first book collection was RTL, the styles were swapped on the first save.  See CommonReaderAppBuilderCore::doBeforeSavingNewApp.  
Use styles that work with direction = RTL or LTR.

PWA: Fix CSS styles so that they work in RTL or LTR

---

convert/convertBooks.ts

Move figure in text to before the next non-verse marker
