sillsdev/appbuilder-pwa

src/lib/data/store-types.js

The prev property of referenceStore had a bug where it would not find the previous chapter if the current chapter was 2.
TL;DR: off by one error.

fixed bug with prev reference property

---

scripts/convertBooks.ts
scripts/convertConfig.ts

The BookCollection has attributes (collectionName, collectionAbbreviation, collectionDescription) that are actually not required to be filled out in the App Builder. 
The Proskomma Freeze process (in convertBooks.ts) depended on collectionAbbreviation being set.  It now falls back to id.

Make BC attributes optional and revert to id for abbr

---

package-lock.json
src/lib/components/Dropdown.svelte
src/lib/components/LayoutOptions.svelte
src/lib/components/SelectGrid.svelte
src/lib/components/Sidebar.svelte
src/lib/components/TabsMenu.svelte

I am seeing quite a few of these messages from different components:
> A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.
Most of these have `` before them.

Upgrade dependencies (include Svelte.Kit to 1.0.0-525)

---

src/lib/components/ScriptureView.svelte
src/lib/data/stores.js

Adding store variables that will allow the text size and line height to be changed immediately.
ScriptureRender is being rewritten for Sofia at the moment, so where these variables may be used in the final version may differ.  But the store that's affected, and will need to be updated by the text view popup, will be the same so that the team working on that feature can see the text change immediately.
To change the font size or line height from a component:
import {
bodyFontSize,
bodyLineHeight
} from '$lib/data/stores';
$bodyFontSize = '30px';
$bodyLineHeight = '300%';
Still to be done (not in this PR): get initial values from configuration

Add stores to allow text size and line spacing changes to be viewed

---

src/lib/app.css
src/lib/components/ScrolledContent.svelte
src/routes/+layout.svelte
src/routes/+page.svelte
src/routes/about/+page.svelte
src/routes/account/+page.svelte
src/routes/bookmarks/+page.svelte
src/routes/highlights/+page.svelte
src/routes/history/+page.svelte
src/routes/notes/+page.svelte
src/routes/search/+page.svelte
src/routes/settings/+page.svelte

* match what web-languageforge does:
- next-app/src/lib/app.css
- next-app/src/routes/+layout.svelte

Fix inclusion of tailwind css directives

---

src/lib/data/store-types.js

The collection id can be derived from $refs.docSet so add a property to $refs for it.
I see places in code for another PR where they are doing:
```
const colId = $refs.docSet.split('_')[1];
```
And then using the colId to look in config.  This should be part of $refs.

Add $refs.collection property derived from $refs.docSet

---

scripts/convertMedia.ts

Rewrote most of the `convertMedia.ts` file. Files in `static/{media folders}` are now deleted before they are copied. I also added incremental compilation, so that only modified folders will be copied.

Delete old files before copying new files in convertMedia.ts

---

src/lib/components/BookSelector.svelte
src/lib/components/ChapterSelector.svelte
src/lib/components/Dropdown.svelte
src/lib/components/SelectGrid.svelte
src/lib/components/TabsMenu.svelte
src/lib/components/TextSelectionToolbar.svelte
src/lib/data/stores/scripture.js

Issues:
Grid CSS for the win!
Before:
After:

Fix issues in Book Selector

---

src/lib/components/TextAppearanceSelector.svelte

When there were two themes, it had two columns but three buttons still.

Fix Text Appearance theme buttons

---

scripts/convertMedia.ts
scripts/convertStyles.ts
scripts/index.ts
src/lib/components/ScriptureViewSofria.svelte
src/routes/+page.svelte
static/override-sab.css

* body and body.* (e.g. body.single) have definitions for margin that were not being used since our app bar and audio toolbar are a part of the body.
* add convertStyles that changes body to #content so that these are picked up.
* add processing of wide pages so that they have max width and centered in page
Fixes #224

Fix issues with margin

---

scripts/convertStyles.ts
scripts/index.ts
src/routes/+layout.svelte

The styles generated are for the body element of the mobile browser window in the Android app.  This browser window doesn't include the app bar or tool bars.  With the PWA, we need to split up the styles assigned to body. Most of the styles will be attached to #container. The margin-top and margin-bottom are changed to padding-top and padding-bottom and attached to the #content element instead.

Split body style into #content and #container styles

---

scripts/convertConfig.ts

* It turns out that there can be multiple translation-mapping sections in the .appDef file. So process them all.

Fix parsing translation-mappings

---

src/lib/components/BookSelector.svelte
src/lib/components/ChapterSelector.svelte
src/lib/components/TabsMenu.svelte

It is not necessary for components to pass in a hardcoded active tab attribute. Neither Book or Chapter selector make use of it, and it makes things complicated for CollectionSelector. If the active tab is set to 'Single Pane' but the 'Single Pane menu is disabled, it will still display the contents since all tabs are being passed to the tab menu despite their visibility:
`showSinglePane: false, showSideBySide: true, showVerseByVerse: true`
It is possible to set the active tab prop to be the 'default layout option' value but Scripture App Builder allows the user to select a disabled layout option as the default. 
Instead, have the tab component menu initialize the active tab to the first available visible tab.

active tab

---

src/lib/components/TextSelectionToolbar.svelte
src/lib/data/bookmarks.ts
src/lib/data/highlights.ts
src/lib/data/notes.ts
src/lib/data/stores/annotation.js

* We have annotation stores (bookmarks, notes, highlights) for the current chapter.  If an annotation is added to the current chapter then these need to be updated but there wasn't a way for these stores to be dependent on the IndexedDB update.
* Introduce a store for when IndexedDB is changes. Greatly simplifies the annotation stores to just use derived().

Add IndexedDB update stores

---

src/lib/components/TextAppearanceSelector.svelte
src/lib/data/stores/view.js
src/routes/+page.svelte

This pull request implements feature #290 by
- Adding a local storage flag that tracks whether or not this launch is the first ever launch
- Displays modal on first launch based on the following conditionals: 
- `firstLaunch`: a store object that contains a boolean of whether or not this is the first launch ever on a device.
- `showColllectionsOnFirstLaunch`: a boolean value pulled from SAB of if the user wants to display the menu on first launch
- `enoughCollections`: a boolean value assigned to true iff there are at least two book collections for the user to choose from.

#290 Feature: Layout Menu on First Launch

---

src/lib/components/ChapterSelector.svelte
src/lib/components/TabsMenu.svelte

Tab Menu was passing cols value as prop to its child component. Not all child components use the cols property so cols was moved to the props handler of the tab props object that is passed to the child.

Resolve Layout 'cols' warning

---

src/lib/components/ColorCard.svelte
src/lib/components/IconCard.svelte

Implements proper text alignment of the main body text of the bookmarks, highlights and notes cards so that it starts after the icon and does not go past the three dot dropdown menu. Fixes issue #308

Implement Text Alignment

---

src/routes/bookmarks/+page.svelte
src/routes/highlights/+page.svelte
src/routes/history/+page.svelte
src/routes/notes/+page.svelte

Added padding inside the card holding div in bookmarks, highlights, history, and notes in order to force proper spacing of the cards from the sides of the page and the top bar. Fixes #332

Implement Padding

---

src/lib/components/ScriptureViewSofria.svelte
src/lib/components/TextSelectionToolbar.svelte
src/lib/data/audio.ts
src/lib/scripts/verseSelectUtil.ts
src/routes/+page.svelte

* The play button plays the audio if verses are selected and audio paused.
* The play and repeat buttons disappear if there are no timing files.
* The audio starts from the verse that is selected closest to the beginning of the chapter.
* If audio is playing, verse selection is disabled.
* Fixes #362.

Enable text selection toolbar play button functionality

---

src/lib/components/ScriptureViewSofria.svelte

Footnote class in root span styles footnote caller incorrectly.
Resolve by removing footnote class from root span.

Bug: Footnote Caller Incorrectly Styled

---

src/lib/components/NoteDialog.svelte

A slight adjustment to the note modal that uses the textArea.value more directly as opposed to passing it through a variable

Simplify Edit Note Modal

---

.github/workflows/lint.yml
README.md
package-lock.json
package.json
src/app.d.ts
src/lib/components/ScriptureViewSofria.svelte
src/lib/components/StackView.svelte
src/lib/data/stores/scripture.js
src/lib/scripts/scripture-reference-utils.test.ts
src/lib/scripts/scripture-reference-utils.ts
src/routes/+page.svelte
vite.config.js

Implements #388
* Develop utilities for parsing in-text references and generating
respective HTML content.
* Develop tests to evaluate effectiveness of developed functions
* Develop footnote content display component with stack functionality.

Feature: Reference Parsing

---

src/lib/components/ScriptureViewSofria.svelte

At this point, ignore figure graft.  At some point need to implement displaying the figure, but for now, this change prevents a figure graft from causing an exception that prevents any page with a figure graft from displaying at all

Figure graft crashes page display

---

scripts/convertConfig.ts

Fixes issue #427
This does not make all the other video types play.  It just avoids the crash by providing default values for nonexistent fields

Videos other than Jesus Film videos crash convertConfig

---

src/lib/components/StackView.svelte
src/routes/+page.svelte

Apply the same font, font size and line height attributes to the footnote as are applied to the standard text.  Makes the reference part bold and the rest the correct height and size.

Apply text font setup to footnote

---

scripts/convertBooks.ts

* For many Bibles, there are illustrations for the print bible and the related`\fig` markers are left in the USFM that are not used in the mobile app. The native app ignores the figs referencing missing illustrations.

During convertBooks, remove figs with missing illustrations

---

src/lib/data/stores/setting.ts

Without the initial value set to an empty map, the array.reduce didn't correctly assign the key,defaultValue for verse-numbers,

Fix setting verse-numbers setting

---

scripts/convertConfig.ts

It is possible to have extra entries in the font-choice items that actually don't exist in the font entries.  SAB native app ignores these.

Fix: font choices in book and collection may have invalid names

---

scripts/convertConfig.ts

* allow it to be optional
* allow it for all audio-sources (FCBH can test with dev server)
* don't use it if it isn't a valid url
* many projects have just "http://" for the address of FCBH audio-source and I don't know why.

Fix audio-source address parsing

---

src/routes/about/+page.svelte

Fixes #461
SAB defines body.about style.  All of the body styles are converted to #container by convertStyles.ts. So insert a dev with id=container and class=about so that the generated style will be picked up.

Fix About page to use styles

---

sab-proskomma/index.ts

Requires next release of SAB after 11.3

Allow dash and space in book collection id

---

src/lib/components/CollectionList.svelte

The style was being generated as style="[object Object]" instead of the real style values.

CollectionList: Fix conversion of style object to string

---

src/lib/components/BookSelector.svelte
src/lib/components/ChapterSelector.svelte
src/lib/components/ScriptureViewSofria.svelte
src/lib/scripts/numeralSystem.test.ts
src/lib/scripts/numeralSystem.ts

Fixes #488 
The following setting in Scripture App Builder controls the numeral system for chapter and verse numbers within a book collection:
This setting can be further customized for each book within a collection:
This fix makes these settings effective for chapter and verse selectors, as the following screenshots show.

Numeral System for Chapter/Verse Navigation

---

src/lib/components/BookSelector.svelte

* Gilaki project does not allow the user to switch from list to grid since there are long names in the book selector for videos.

For book selector, use config if user setting not available

---

src/lib/data/language.test.ts
src/lib/data/language.ts
src/lib/data/stores/localization.js
src/lib/data/stores/setting.ts

Fixes #487 
On the Appearance > Interface > Languages page in SAB, there are preferences for which language to use:
If the app is configured to use the system language as default, it obtains preferred languages from the browser and compares them to available UI translations.  If a matching translation is found (or a similar one, ex: en-US instead of en-UK), this is the default language.  Otherwise, the app will use the fallback language specified in SAB.
The logic for choosing a language that matches the user's preference is found in `getDefaultLanguage()` in `src/lib/data/language.ts`.
The following screenshots demonstrate how the "Preferred Language" setting in Google Chrome affects the default language in the app on a mobile device.

Detect System Language of Browser

---

src/lib/components/Modal.svelte
src/lib/components/NoteDialog.svelte
src/lib/components/ScriptureViewSofria.svelte

Fixes #490 
The user may click on a note icon next to a verse to view the note in a modal popup.  In the modal, the user can tap a pencil icon to edit the note.

Tap on note icon to view or edit

---

scripts/convertConfig.ts
scripts/convertMarkdown.test.ts
scripts/convertMarkdown.ts

Fixes #515
During the conversion process, SAB converts supported Markdown in footers to HTML.
The footers for the Book Collection are rendered at the bottom of each page, as the screenshot below shows.  However, as issue #516 explains, the PWA currently ignores book-specific footers.

Footer: Display Markdown as HTML

---

src/lib/data/scripture.js

We need to use SABProskomma in runtime so that the lang check matches

Use SABProskomma

---

src/routes/bookmarks/+page.svelte
src/routes/highlights/+page.svelte
src/routes/notes/+page.svelte

Fixes #541
Works the same as "display message when there is no history". For the bookmarks, highlights, and notes,
when there is no annotation, display a message.
This way it does not look like an error.

Display message when there are no annotations

---

.gitignore
convert/convertBooks.ts
convert/convertConfig.ts
convert/convertMedia.ts
convert/stringUtils.ts

Partially fixes #500.
Converts quiz books from SFM to usable JSON.
Copies default audio provided by SAB to `static/assets/*`.
Also ignores null `<traits></traits>` in `appdef.xml`, although this may not be a necessary change, as it was only an issue when there were no standard scripture books defined for the app, which caused other problems.

Feature/convert quiz #500

---

convert/convertContents.ts

Handle link type "other" such as: ```<link type="other" location="layout" />```
Add a linkLocation field to the contents entries and set linkTarget to "" if not defined.
For website entries ( ```<link type="other" location="website" target="https://www.sil.org" /> ```) fill in both fields.

Issue #560 - Convert Content crashes on "other" link entries

---

convert/convertBooks.ts

Per @chrisvire 's request, switched quiz conversion to store quizzes in a folder named after the parent collection instead of the docSet.
The primary rationale is that docSet is a Proskomma specific entity, rather than one specific to an SAB project, unlike book collections.

Fix quiz conversion process regarding collections

---

convert/convertBadges.ts
convert/convertMedia.ts

* When runing `npm run dev`, if the developer switched projects, then convertMedia was getting a list of all the files changed and copying everything instead of filtering by triggerFiles
* The better change would likely be to filter it on the outside. However, then we would need to change the interface to be triggerFiles and triggerFolders since we would need to process them differently.
* Also fix how badges are processed to only include english is actually sharing apple app link.
* also, clean up the folder if it already exists and not sharing.

fix copying data to static folder during dev script

---

src/lib/data/stores/reference.ts

Switching between projects using `Run PWA` was failing.  I noticed that the failure was in starting due to differences in collections.  This only uses the saved last reference if it is the same package as before.

Only use localstorage.refs if it is the same package

---

src/routes/share/+page.svelte

When sharing the app, share using the sharesheet instead of just linking to the store.

Share using Sharesheet

---

src/lib/components/Navbar.svelte

On parent component, add `on:backNavigation={handler}` to `NavBar` component. In handler, call `event.preventDefault()` to prevent the default behavior of going back to the main page.

Allow custom backNavigation

---

src/routes/share/+page.js

* We only need the badges/languages.json if we are sharing an apple app link.

Disable fetching badge information when not needed

---

convert/convertContents.ts
src/routes/contents/[id]/+page.svelte

- fixes issue #582
- adds the audio icon in the appropriate place if there is audio in the contents menu item
- changes the onclick to go to the playAudio() fuction instead of navigating if the
icon is clicked
- playAudio() function plays the correct audio based on the interface language
- also changes the formatting of the html to use <div> instead of <a> as per an update in the css
- potential issue: the way I go about playing the audio instead of navigating could be too
complicated/might not be neccessary if there is a
different way it should work (z-index?)

play contents menu audio clips

---

src/lib/components/Slider.svelte

Fixes svelte-check warnings about CSS compatibility in Slider.svelte
Defines the `appearance` style to match `-webkit-appearance`

Define styles for compatability in Slider.svelte

---

src/lib/components/TextAppearanceSelector.svelte
src/lib/data/stores/view.js
src/routes/+layout.svelte
src/routes/contents/[id]/+page.svelte

fixes issue #537, contents text size should be
adjustable
- shows the modal for text TextAppearance if the setting is true
- adds a contentsMdoe to TextAppearanceSelector
- shows only the options that need to be shown if its in contents mode
- creates a seperate contentsTextSize

add text appearance selector to contents menu

---

convert/convertConfig.ts

starting implementation of issue #622
converts the plans section in appdef.xml to json

parse plans in convertConfig

---

convert/convertBooks.ts

Replaces call to fs.rmdirSync() with fs.rmSync().
See npm deprecation [DEP0147](https://nodejs.org/api/deprecations.html#DEP0147)

Fix deprecated call to filesystem

---

src/routes/text/+page.svelte

In the src/routes/text/+page.svelte modifications are made to read in the 'Allow Swiping Between Books' feature and prevent swiping between books and make the proper arrows invisible if the option is disabled

Disable swipe between books when config is diabled #632

---

convert/convertConfig.ts
src/lib/components/LayoutOptions.svelte
src/lib/data/stores/collection.ts

In 12.1, the feature name that controls whether a collection is allowed in single-pane mode changed
from: bc-allow-single-pane
to:   bc-layout-allow-single-pane

Use correct allow-single-pane feature in 12.1

---

convert/index.ts
src/lib/components/ScriptureViewSofria.svelte

Some convert scripts are only necessary for SAB, and some in the future will only be neccessary for DAB. This pull request:
-Separates the list of convert scripts into common, SAB only, and a future DAB only
-Uses programType from ConvertConfig (which comes from appdef.xml) to determine which lists to use

#681 Run Convert Scripts Based on Project Type

---

convert/convertConfig.ts

In DAB 12.2, audio-sources is always there, but it might not have audio-source elements in it.

DAB 12.2: Make audio-source optional in audio-sources

---

.gitignore

There are times when I need to compare data from different apps or data generated by different version of SAB/DAB.  So I have been copying the data to something like "data-sab", "data-12.1.1", etc.
I don't want these showing up in the changed files.`
Since we already had data-sandbox as a source directory, I had to do a bit of fudging with the patterns so that new files in that directory would not be ignored, but the data-sandbox/node_modules would still be ignored. Ugh.

Ignore temporary data directories with the namng pattern data-XXX

---

convert/convertBooks.ts

The EBV app from `joop` on the community site had files with large amounts of whitespace that would generate warnings in Proskomma.
https://community.scripture.software.sil.org/t/pwa-on-12-2-2-for-mac/4609

ConvertBooks: Trim whitespace at end of lines

---

convert/convertBooks.ts

When filenames can contain non-ascii characters, make sure to normalize each part of the comparison.
This happened when usfm files had non-ascii characters and they are split up into multiple chucks and we have to combine them back together.
Used ChatGPT
https://chatgpt.com/share/672277fc-0a14-8006-8fe9-2b31b732de1f

Compare files using normalize for non-ascii chars

---

config/index.d.ts
convert/convertBooks.ts
convert/convertConfig.ts
src/lib/components/BookSelector.svelte
src/lib/components/ChapterSelector.svelte
src/lib/components/HtmlBookView.svelte
src/lib/components/ScriptureViewSofria.svelte
src/lib/data/catalogData.ts
src/lib/data/navigation.test.ts
src/lib/data/navigation.ts
src/lib/data/stores/reference.ts
src/lib/data/stores/scripture.js
src/lib/scripts/configUtils.ts
src/routes/text/+page.js
src/routes/text/+page.svelte

Sample project provided by user: https://www.evangelischebijbelvertaling.nl/EBV.zip

Display html books

---

convert/convertBooks.ts

The UI for displaying the build in App Builders updates when there is a newline. Change the display of book ids being processed so that there is a newline every 10 books.

Improve display of book ids in App Builders

---

src/lib/search-worker/data/pk-verse-provider.ts
src/lib/search-worker/data/test/pk-verse-provider.test.ts

When search was written, somehow the document type was set to book and now it is not. So search wasn't searching any books.

Fix search; don't filter books

---

src/lib/data/audio.ts
src/lib/navigate/index.ts
src/routes/text/+page.svelte

Currently, the audio keeps playing when navigating to another location or displaying a different route. It should stop.
We have to be careful about not breaking the auto play between chapters.

Stop audio when navigating to another ref or route

---

convert/index.ts

* Even though DAB doesn't have contents menu, the template depends on importing at least an empty contents.js file

Add convertContents to DAB

---

convert/convertBooks.ts
src/lib/components/ScriptureViewSofria.svelte

* HACK: Add NO_CAPTION to figs without captions and don't render it
* Always display figures or videos in non-scripture books

Fix issues with displaying figures

---

src/lib/components/BookSelector.svelte
src/lib/components/ChapterSelector.svelte

When a chapter is selected that has no verses, then initiate the navigation immediately.

Fix navigate with show verse selector and no verses

---

convert/convertBooks.ts

SAB support `\fig filename.png\fig*` but the standard requires `\fig |src="filename.png"\fig*` (and Proskomma breaks without a caption).

Support \fig with just filename

---

src/lib/video/index.ts

The method signature called for an array of strings.  The features include boolean types and perhaps others.   Changing the type to any removes errors being detected in the locations where it is called.

Allow for non string features in method signature.

---

src/lib/components/ScriptureViewSofria.svelte

This fixes a crash on trying to process a reading plan made of tables.  We still have an issue that for this case, selecting chapter 1 is still returning the entire book from Proskomma

Crash on reading plan book selected

---

convert/convertConfig.ts

In SAB, you can configure an audio entry that has a timing file but without an audio file. It is not useful, but it is allowed.
Change the conversion of the appdef.xml to config.json to ignore audio entries without file sub-entries.

Support converting audio element without file

---

src/routes/contents/[id]/+page.svelte

If the contents item doesn't specify a book collection, analytics callback logging history failed with unfilled promise error

Fix analytics error when contents item selected

---

convert/convertBooks.ts

There is a bug in Proskomma where the generation of events is messed up if you have a series of table row markers \tr.  A work-around is to put paragraph makers \p around the series of table row markers.

Add paragraphs around table rows

---

convert/convertMarkdown.test.ts
convert/convertMarkdown.ts
src/lib/components/ScriptureViewSofria.svelte

We were using milestones for web, email, and tel urls, but this didn't work when they were in \s headings. Proskomma doesn't support \jmp yet. Pass these links through as /jmp and convert in ScriptureViewSofria. When Proskomma supports \jmp, switch and remove convertJmp code.

HACK: switch web, email, tel urls to use embedded /jmp

---

.gitignore

On some lame platforms (Windows), there are vite temp files left behind
Ex: vite.config.js.timestamp-1738015073323-88f028b10ca2c.mjs

Ignore vite temp files

---

package-lock.json
package.json

svelte-gestures 5.1.3 only works with Svelte 5 syntax. When we switch the code to Svelte 5 that uses svelte-gestures, then we will need to upgrade it again.

Revert svelte-gestures to 5.0.7 which works with Svelte 4
